name: Deploy on the Server

on:
  workflow_call:

jobs:
  deploy-on-server:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          password: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Starting Deployment"
            mkdir devops
