# san the docker file for issues or common vurnabilities
name: Docker lint

on:
  workflow_call:

jobs:
  docker-linting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Validate Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: C:\Users\Pragya Malik\OneDrive\python-for-devops\GitHub-Actions\My-DevOps-Journey\Docker\Delish-Project-docker-updates\dockerfile
